apiVersion: osbuilder.project-flotta.io/v1alpha1
kind: OSBuildConfig
metadata:
  name: flotta
spec:
  details:
    distribution: rhel8
    targetImage:
      architecture: x86_64
      targetImageType: edge-container
      osTree:
        url: "https://hostedimagesserver.flotta.io/"
        ref: "rhel/8/x86_64/edge"
  template:
    osBuildConfigTemplateRef: flotta-template
    parameters:
      - name: REPO_URL
        value: https://hostedimagesserver.flotta.io
  triggers:
    configChange: true